## Assignment 4 Solutions
Author: Laura Bissoltan

### Problem 1

In [3]:
#1.1
import numpy as np
A = np.array([\
             [3,-1,-1,0,0,0],\
             [-1,4,-1,-1,0,0],\
             [-1,-1,4,-1,-1,0],\
             [0,-1,-1,4,-1,-1],\
             [0,0,-1,-1,4,-1],\
             [0,0,0,-1,-1,3]],float)
b=np.array([5,5,0,0,0,0],float)
n=len(b)

def Jacobi(A,b,x0,imax):
    x0=np.zeros(b.shape)    
    xr=np.zeros(x0.shape)
    
    for k in range(imax):
        for i in range(n):
            xr[i] = (b[i] - np.dot(A[i, :i], x0[:i]) - np.dot(A[i, i + 1:], x0[i + 1:])) / A[i, i]
        x0 = xr
       #print(xr)
    return xr


VJ=Jacobi(A,b,0,10)
print("V_J:",VJ)        
print("i", A[0,0])
        
    

V_J: [3.63037551 3.33649669 2.63941992 2.16069752 1.49926332 1.21998694]
i 3.0


In [56]:
#1.2

n=len(b)

def Seidel(A,b,x0,imax):
    x0=np.zeros(b.shape)    
    xr=np.zeros(x0.shape)
    
    for k in range(0,imax):
        for i in range(0,n):
            s=0
            for j in range(0,i):
                s=s+A[i,j]*xr[j]
            for j in range(i+1,n):
                s=s+A[i,j]*x0[j]
            xr[i]=(b[i]-s)/A[i,i]
            x0=xr
        #print(xr)
    return xr  

GS=Seidel(A,b,0,10)
print("V_GS:", GS)

V_GS: [3.65537747 3.36143587 2.66719859 2.1854602  1.51749645 1.23431888]


In [57]:
#1.4

V=np.linalg.solve(A,b)
print("The true solution vector V:",V)
print("V_i", "  Relative error for V_J", "   Relative error for V_GS")
for i in range(0,6):
    r_e1=((V[i]-GS[i])/V[i])*100
    r_e2=((V[i]-VJ[i])/V[i])*100
    print(f'{i:2} {"    "} {r_e2:12.15f} {"        "} {r_e1:12.15f}')


The true solution vector V: [3.7254902  3.43137255 2.74509804 2.25490196 1.56862745 1.2745098 ]
V_i   Relative error for V_J    Relative error for V_GS
 0      2.553078495105462          1.881973135442747
 1      2.764953513898025          2.038154643910595
 2      3.849702902829611          2.837765660236629
 3      4.177762355672825          3.079591118536765
 4      4.421963623414503          3.259601379696455
 5      4.277947491156613          3.153441482089482


### Problem 2

In [58]:
#2
from math import sqrt
A = np.array([\
            [450,-200,0],\
            [-240,420,-180],\
            [0,-225,225]])
eigenvalues, vectors = np.linalg.eig(A)
print("i", "   sqrt(ith_eigenvalue)" "           eigenvector")
for i in range(1,4):
    print(f'{i} {"   "} {sqrt(eigenvalues[i-1]):10.15} {"   "} {vectors[:,i-1]}')


i    sqrt(ith_eigenvalue)           eigenvector
1     26.4310081187959     [-0.58785405  0.73069726 -0.34714424]
2     18.4249256953321     [-0.63435541 -0.3505515   0.68898973]
3     7.54479442699637     [0.29129699 0.57250939 0.76640659]


### Problem 3

In [59]:
#3.1
import numpy as np

def qrgram(A):
   
    (m,n)=A.shape
    Q=np.zeros((m,n))
    R=np.zeros((n,n))
    
    for j in range(0,n):
        u=A[:,j]
        for i in range(0,j):
            R[i,j]=np.matmul(np.transpose(Q[:,i]),A[:,j])
            u=u-R[i,j]*Q[:,i]
        R[j,j]=np.linalg.norm(u)
        Q[:,j]=u/R[j,j]
    return Q,R



In [60]:
#3.2

A = np.array([[-10,13,7,-11],\
            [2,1,-5,3],\
            [-6,3,13,-3],\
            [16,-16,-2,5],\
            [2,1,-5,-7]])

Q, R = qrgram(A)
print("QR decomposition of a real matrix A:\n", Q)
print(R)

QR decomposition of a real matrix A:
 [[-5.00000000e-01  5.00000000e-01  5.77350269e-01 -1.88411095e-16]
 [ 1.00000000e-01  5.00000000e-01  0.00000000e+00  7.07106781e-01]
 [-3.00000000e-01 -5.00000000e-01  5.77350269e-01 -1.88411095e-16]
 [ 8.00000000e-01  0.00000000e+00  5.77350269e-01 -1.88411095e-16]
 [ 1.00000000e-01  5.00000000e-01  0.00000000e+00 -7.07106781e-01]]
[[ 20.         -20.         -10.          10.        ]
 [  0.           6.          -8.          -6.        ]
 [  0.           0.          10.39230485  -5.19615242]
 [  0.           0.           0.           7.07106781]]
